---
apiVersion: apps/v1
kind: Deployment
metadata:  
  name: nginx-deployment  
  labels: 
    type: webserver
    author: intelliqit

spec:  
  replicas: 2
  strategy:  
    type: Recreate  
  selector:  
    matchLabels:  
      type: proxy

  template: 
    metadata: 
     name: nginx-pod
     labels: 
       type: proxy  
    spec: 
     containers: 
      - name: mynginx
        image: nginx:1.24
...             

