---
apiVersion: v1
kind: Pod
metadata:  
  name: tomcat-pod
  labels:
    type: appserver

spec:  
  containers:  
   - name: tomcat-pod
     image: tomee
  affinity:  
   nodeaffinity:  
     requiredDuringSchedulingIgnoredDuringExecution:  
       nodeSelectorTerms:
        - matchExpressions:  
          - key: slave1
            values: 
              - intelliqit1 
            operator: In  
...              
     
    
