---
apiVersion: v1
kind: Pod
metadata:  
  name: nginx-pod
  labels:  
    type: proxy
    value: intelliqit

spec: 
 containers:  
   - name: mynginx
     image: nginx
 affinity:  
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms:  
          - matchExpressions:
            - key: slave3
              values: 
               - intelliqit1
              operator: In    
...                 
                    
           
      
