---
apiVersion: v1
kind: Pod
metadata:  
 name: mysql-pod
 labels: 
  type: db
  author: intelliqit

spec:  
 containers:  
   - name: mydeb
     image: mysql:5
     env:  
      - name: MYSQL_ROOT_PASSWORD
        value: intelliqit

...          

