---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:  
 name: task-pv-claim
 labels:  
  author: intelliqit

spec:  
 storageClassName: manual
 accessModes: 
  - ReadWriteOnce
 resources: 
  requests:  
    storage: 3Gi
...

         
