---
apiVersion: v1
kind: ReplicationController
metadata:  
  name: httpd-rc
  labels:  
    type: webserver
    author: intelliqit

spec:  
 replicas: 3
 template:  
   metadata:  
     name: httpd-pod
     labels:  
      type: webserver   
   spec:
    containers:  
     - name: myhttpd
       image: httpd
       ports:  
        - containerPort: 8080
          hostPort: 6060
...
            

