---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: result-app-deployment
 labels:  
   type: result-app
   author: intelliqit

spec:
 replicas: 2   
 selector:  
  matchLabels:
   name: result-app

 template:  
  metadata:  
    name: result-app-pod
    labels:  
     name: result-app  
  spec:  
   containers:  
    - name: result-app-pod
      image: dockersamples/examplevotingapp_result

...        
     
     
   
